# Analiza podataka

In [11]:
import sys
from pathlib import Path

RANDOM_STATE = 42

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [12]:
import pandas as pd

df = pd.read_csv("../data/processed/articles.csv", sep=";", encoding="utf-8-sig")

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5202 entries, 0 to 5201
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source          5202 non-null   str
 1   url             5202 non-null   str
 2   title           5202 non-null   str
 3   published_date  5202 non-null   str
 4   text            5202 non-null   str
dtypes: str(5)
memory usage: 203.3 KB
None

In [13]:
df.head()

,source,url,title,published_date,text
0,Blic,https://www.blic.rs/vesti/politika/3-opcije-na...,SRBIJA NA POLITIČKOJ RASKRSNICI! Tri rešenja n...,2025-01-28,"Tri opcije za rešenje krize: nova vlada, novi ..."
1,Blic,https://www.blic.rs/vesti/drustvo/akademska-go...,AKADEMSKA GODINA IZGUBLJENA? Profesorka i deka...,2025-05-21,Blokade fakulteta u Srbiji traju šest meseci D...
2,Blic,https://www.blic.rs/vesti/politika/aleksandar-...,"""OSTAĆU SAMO ČLAN SNS"" Šapić o članstvu u Pokr...",2025-05-27,Aleksandar Šapić je izjavio da kašnjenja u rad...
3,Blic,https://www.blic.rs/vesti/politika/aleksandar-...,"""DOK SAM JA POLITIČKI ŽIV, ĐILAS SIGURNO NEĆE ...",2025-02-13,Šapić istakao da se nikada nije skrivao iza Al...
4,Blic,https://www.blic.rs/vesti/politika/aleksandar-...,"""IZBORA ĆE BITI"" Vučić u Tirani, otkrio kada j...",2025-05-16,Izbori će se održati prema odlukama institucij...

In [14]:
df.isna().sum()

source            0
url               0
title             0
published_date    0
text              0
dtype: int64

In [15]:
df["text_length"] = df["text"].astype(str).str.len()

df[["source", "title", "text_length"]].sort_values("text_length").head(20)

        source                                              title  text_length
2201        N1  Promene na novom studentskom sajtu: Sat i dalj...          116
2862      Nova  Incident na Pravnom fakultetu: Napadnute profe...          138
2303        N1  Studenti u blokadi Pravnog u Nišu: BIA pokušav...          138
4278  Politika      Десета београдска гимназија излази из блокаде          139
4299  Politika  Довели дете да вређа студенте који желе да уче...          147
2059        N1  Maturanti više beogradskih gimnazija najavili ...          155
2002        N1  Građani pozvani da u 11.52 zastanu na 15 minut...          158
2401        N1  Završen četvrti sastanak dekana Filozofskog fa...          159
4983  Politika  Студенти у Пионирском парку нападнути шипкама ...          159
4321  Politika       Факултет за физичку хемију изашао из блокаде          163
1949        N1  Čipčić: Svim srcem i dušom sam uz studente, u ...          164
2287        N1  Studenti PMF-a tokom blokade napravili aplikac...          191
3394      Nova  Priveden student koji je napao profesorku i st...          213
2013        N1  Incident na blokadi u Beogradu: Vozač prošao k...          215
5006  Politika             Светлошћу против мрака блокада (видео)          216
4087  Politika  Активисти опозиције поново блокирају град (видео)          220
4743  Politika           Претње студентима: Долазим да вас убијем          222
4952  Politika  Студенти поднели нову кривичну пријаву против ...          224
2039        N1  Koje sve javne ličnosti su do sada stale uz st...          225
4628  Politika                       Опозиција присвојила протест          227

In [17]:
df["source"].value_counts()

source
Nova        1672
Politika    1121
Danas        895
Blic         765
N1           530
Kurir        219
Name: count, dtype: int64